#include "events.h"
#include "ev_handler.h"
static struct ev_handler evhandler_array[] = {
 { .handler = ev_move_window_x, .name = "ev_move_window_x" },
 { .handler = ev_move_window_y, .name = "ev_move_window_y" },
 { .handler = ev_move_window_upleft, .name = "ev_move_window_upleft" },
 { .handler = ev_move_window_upright, .name = "ev_move_window_upright" },
 { .handler = ev_move_window_downleft, .name = "ev_move_window_downleft" },
 { .handler = ev_move_window_downright, .name = "ev_move_window_downright" },
 { .handler = ev_delete_window, .name = "ev_delete_window" },
 { .handler = ev_info_window, .name = "ev_info_window" },
 { .handler = ev_maximise_window, .name = "ev_maximise_window" },
 { .handler = ev_maximise_window_vert, .name = "ev_maximise_window_vert" },
 { .handler = ev_fix_window, .name = "ev_fix_window" },
 { .handler = ev_exec_command, .name = "ev_exec_command" },
 { .handler = ev_next_focus, .name = "ev_next_focus" },
 { .handler = ev_switch_vdesk, .name = "ev_switch_vdesk" },
 { .handler = ev_next_vdesk, .name = "ev_next_vdesk" },
 { .handler = ev_prev_vdesk, .name = "ev_prev_vdesk" },
 { .handler = ev_fix_next_vdesk, .name = "ev_fix_next_vdesk" },
 { .handler = ev_fix_prev_vdesk, .name = "ev_fix_prev_vdesk" },
 { .handler = ev_up_focus, .name = "ev_up_focus" },
 { .handler = ev_down_focus, .name = "ev_down_focus" },
 { .handler = ev_right_focus, .name = "ev_right_focus" },
 { .handler = ev_left_focus, .name = "ev_left_focus" },
 { .handler = ev_upleft_focus, .name = "ev_upleft_focus" },
 { .handler = ev_upright_focus, .name = "ev_upright_focus" },
 { .handler = ev_downleft_focus, .name = "ev_downleft_focus" },
 { .handler = ev_downright_focus, .name = "ev_downright_focus" },
 { .handler = ev_wm_quit, .name = "ev_wm_quit" },
 { .handler = ev_wm_restart, .name = "ev_wm_restart" },
 { .handler = ev_mark_client, .name = "ev_mark_client" },
 { .handler = ev_goto_mark, .name = "ev_goto_mark" },
 { .handler = ev_warp_pointer_x, .name = "ev_warp_pointer_x" },
 { .handler = ev_warp_pointer_y, .name = "ev_warp_pointer_y" },
 { .handler = ev_set_mode, .name = "ev_set_mode" },
 { .handler = ev_raise_window, .name = "ev_raise_window" },
 { .handler = ev_lower_window, .name = "ev_lower_window" },
 { .handler = ev_mouse_move, .name = "ev_mouse_move" },
 { .handler = ev_mouse_resize, .name = "ev_mouse_resize" },
 { .handler = ev_resize_window_x, .name = "ev_resize_window_x" },
 { .handler = ev_resize_window_y, .name = "ev_resize_window_y" },
 { .handler = ev_do_nothing, .name = "ev_do_nothing" },
};
void * evhandler_array_start = evhandler_array;
int evhandler_num = 40;
